### ISSUE TITLE
Issues with Default Buildroot System Image

### ISSUE THREAD

**Issue by lakshanthad** [Seeed-Studio/seeed-linux-buildroot#2]
The following are the issues when running the latest system image on reTerminal:

- [x] spidev_test tool not working. It needs to be put inside the system image and recompile
- [x] CSI Camera need 3rd party software to work
- [x] Micro-HDMI hot-plug feature not working
- [x] Add reTerminal Python Library into the system image - https://github.com/Seeed-Studio/Seeed_Python_ReTerminal
- [ ] Accelerometer + Buttons Python demo has problems with asyncio
- [x] Qt app "SHUTDOWN" button not working because "shutdown now" is not available in Buildroot
- [x] Current directory location is not shown on terminal

**Comment by WillYouth** [comment]
I got these lines of code during compilation and didn't get any files in `output/images`.
```
In file included from /home/pi/seeed-linux-buildroot/output/host/aarch64-buildroot-linux-gnu/sysroot/usr/include/linux/fs.h:19,
                 from ../../../../libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.cpp:75:
/home/pi/seeed-linux-buildroot/output/host/aarch64-buildroot-linux-gnu/sysroot/usr/include/linux/mount.h:92:6: error: multiple definition of ‘enum fsconfig_command’
   92 | enum fsconfig_command {
      |      ^~~~~~~~~~~~~~~~
In file included from ../../../../libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.cpp:62:
/home/pi/seeed-linux-buildroot/output/build/host-gcc-final-11.3.0/build/gcc/include-fixed/sys/mount.h:249:6: note: previous definition here
  249 | enum fsconfig_command
      |      ^~~~~~~~~~~~~~~~
```

**Comment by is-qian** [comment]
> I got these lines of code during compilation and didn't get any files in `output/images`.
> 
> ```
> In file included from /home/pi/seeed-linux-buildroot/output/host/aarch64-buildroot-linux-gnu/sysroot/usr/include/linux/fs.h:19,
>                  from ../../../../libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.cpp:75:
> /home/pi/seeed-linux-buildroot/output/host/aarch64-buildroot-linux-gnu/sysroot/usr/include/linux/mount.h:92:6: error: multiple definition of ‘enum fsconfig_command’
>    92 | enum fsconfig_command {
>       |      ^~~~~~~~~~~~~~~~
> In file included from ../../../../libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.cpp:62:
> /home/pi/seeed-linux-buildroot/output/build/host-gcc-final-11.3.0/build/gcc/include-fixed/sys/mount.h:249:6: note: previous definition here
>   249 | enum fsconfig_command
>       |      ^~~~~~~~~~~~~~~~
> ```
> 
> Update: it's a compilation on reTerminal

This issue has been resolved in the upstream repository of buildroot, and the upstream code has been synchronized now.

**Comment by is-qian** [comment]
If you still run into this problem, you can reopen the issue.
